version: '3.3'

services:
    app:
        image: my/app
        build:
            context: .
            dockerfile: Dockerfile

        depends_on:
            - redis

        ports:
            - "8080:8080"
    
    redis:
        image: redis