version: '3.3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: moongod101/docker-swarm-express-playground-node-express

        depends_on:
            - redis

        ports:
            - "8080:8080"
    
    redis:
        image: redis
