version: '3.3'

services:
    app:
        build:
            name: docker.pkg.github.com/felixfong227/docker-swarm-express-playground/node-expressjs:latest
            context: .
            dockerfile: Dockerfile

        depends_on:
            - redis

        ports:
            - "8080:8080"
    
    redis:
        image: redis