name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login docker.pkg.github.com -u USERNAME -p ${{ secrets.GITHUB_TOKEN }}
        docker build --tag docker tag IMAGE_ID docker.pkg.github.com/felixfong227/docker-swarm-express-playground/node-expressjs .
        docker push docker.pkg.github.com/felixfong227/docker-swarm-express-playground/node-expressjs
